# Generated by Django 4.2 on 2023-04-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_service", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="being_delivered",
            new_name="ordered_status",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="description_short",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="order",
            name="ordered",
        ),
        migrations.RemoveField(
            model_name="order",
            name="received",
        ),
        migrations.RemoveField(
            model_name="order",
            name="ref_code",
        ),
        migrations.RemoveField(
            model_name="order",
            name="refund_granted",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="ordered",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description_long",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock_no",
        ),
        migrations.RemoveField(
            model_name="refund",
            name="accepted",
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
